workflows:
  android-kivy-build:
    name: Build Kivy Android APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_HOME: /Users/builder/Library/Android/sdk
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        PATH: /Users/builder/Library/Android/sdk/cmdline-tools/latest/bin:$PATH:$HOME/.pyenv/bin
    scripts:
      - echo "pyenv ve Python ayarları yapılıyor..."
      - export PATH="$HOME/.pyenv/bin:$PATH"
      - eval "$(pyenv init --path)"
      - eval "$(pyenv init -)"
      - pyenv install -s 3.10.13
      - pyenv global 3.10.13
      - python --version

      - echo "pip güncelleniyor ve bağımlılıklar kuruluyor..."
      - python -m ensurepip --upgrade
      - pip install --upgrade pip
      - pip install Cython==0.29.36
      - pip install buildozer==1.5.0
      - pip install virtualenv

      - echo "Android SDK lisansları kabul ediliyor..."
