workflows:
  android-kivy-build:
    name: Build Kivy Android APK
    max_build_duration: 60
    environment:
      flutter: "false"
      xcode: "false"
    scripts:
      - name: Install system dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip zlib1g-dev python3-pip python3-dev git
      - name: Install Buildozer & Kivy
        script: |
          pip3 install --user buildozer kivy
          export PATH=$PATH:$HOME/.local/bin
      - name: Run Buildozer
        script: |
          buildozer --version
          buildozer android debug
    artifacts:
      - buildozer/bin/*.apk
