workflows:
  android-kivy-build:
    name: Build Kivy Android APK
    os: linux                      # burada Linux runner seçiliyor
    max_build_duration: 60         # dakika cinsinden zaman limiti
    environment:
      vars:
        ANDROID_API_LEVEL: 31
        ANDROID_BUILD_TOOLS_VERSION: "30.0.3"
        ANDROID_NDK_VERSION: "23b"
    scripts:
      - name: Install system dependencies
        script: |
          apt-get update
          apt-get install -y openjdk-11-jdk unzip zlib1g-dev python3-pip python3-dev git
      - name: Install Buildozer & Kivy
        script: |
          pip3 install --user buildozer kivy PyDatePicker
          export PATH=$PATH:$HOME/.local/bin
      - name: Run Buildozer
        script: |
          buildozer --verbose android debug
    artifacts:
      - buildozer/bin/*.apk
    publishing:
      email:
        recipients:
          - you@example.com

          - moclabel01@gmail.com
