workflows:
  android-kivy-build:
    name: Build Kivy Android APK
    max_build_duration: 60  # dakika
    machine:
      type: linux-medium
    environment:
      vars:
        ANDROID_API_LEVEL: 31
        ANDROID_BUILD_TOOLS_VERSION: "30.0.3"
        ANDROID_NDK_VERSION: "23b"
        JAVA_TOOL_OPTIONS: "-Xmx2048m"
    scripts:
      - name: Update packages & install system deps
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip zlib1g-dev python3-pip python3-dev git
      - name: Install Python & Buildozer
        script: |
          pip3 install --user buildozer kivy PyDatePicker
          echo 'export PATH=$PATH:$HOME/.local/bin' >> $HOME/.bashrc
          source $HOME/.bashrc
      - name: Run Buildozer
        script: |
          buildozer --verbose android debug
    artifacts:
      - buildozer/bin/*.apk
    publishing:
      email:
        recipients:
          - moclabel01@gmail.com
