workflows:
  android-kivy-build:
    name: Build Android APK on Mac mini M2
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: /Users/builder/Library/Android/sdk
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
        # Yukarıdaki Java yolunu ` /usr/libexec/java_home -v 1.8` komutu çıktısına göre ayarlayın
    scripts:
      - name: Update Homebrew and install dependencies
        script: |
          brew update
          brew install autoconf automake libtool pkg-config
      - name: Install Python 3.10
        script: |
          brew install python@3.10
      - name: Setup Java 8 environment
        script: |
          export JAVA_HOME=$JAVA_HOME
          echo "JAVA_HOME set to $JAVA_HOME"
      - name: Accept Android SDK licenses
        script: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
      - name: Install required Android SDK packages
        script: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
      - name: Install buildozer
        script: |
          pip3 install --upgrade buildozer
      - name: Build APK
        script: |
          buildozer android debug
    artifacts:
      - bin/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
