workflows:
  android-kivy-build:
    name: Build APK with Buildozer
    max_build_duration: 60
    environment:
      vars:
        LC_ALL: "en_US.UTF-8"
        LANG: "en_US.UTF-8"
        ANDROID_HOME: "$HOME/Library/Android/sdk"
        PATH: "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
    scripts:
      - name: Install Python & system deps
        script: |
          brew install python@3.10
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install buildozer Cython

      - name: Install Android SDK & accept licenses
        script: |
          brew install --cask android-commandlinetools
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build APK with Buildozer
        script: |
          buildozer android debug

    artifacts:
      - build/*.apk

