workflows:
  android-kivy-build:
    name: Android Kivy Build
    environment:
      vars:
        ANDROID_SDK_ROOT: /Users/builder/.buildozer/android/platform/android-sdk
      # Mac mini M2 için ortam ayarları
      flutter: stable
      os: macos
    scripts:
      - name: Accept Android SDK licenses
        script: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
      - name: Update SDK packages
        script: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --update
      - name: Build APK with Buildozer
        script: buildozer android debug
    artifacts:
      - app/build/outputs/**/*.apk

