workflows:
  android-kivy-build:
    environment:
      vars:
        ANDROID_HOME: "$HOME/Library/Android/sdk"
        PATH: "$PATH:$HOME/Library/Android/sdk/platform-tools"
      node: stable
      flutter: stable
    scripts:
      - name: Accept Android SDK licenses
        script: |
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
      - name: Install dependencies
        script: |
          brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer
      - name: Build APK
        script: |
          buildozer android debug
    artifacts:
      - build/bin/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com

macos:
  xcode: latest
