workflows:
  kivy-macos-build:
    name: Build APK on macOS (M2)
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies via Homebrew
        script: |
          brew install python3
          pip3 install --upgrade pip setuptools wheel
          pip3 install --user buildozer cython kivy
          echo 'export PATH=$PATH:$HOME/Library/Python/3.*/bin' >> $HOME/.bash_profile
      - name: Install Android SDK via Homebrew
        script: |
          brew install --cask android-sdk
          echo 'export ANDROID_HOME=/usr/local/share/android-sdk' >> $HOME/.bash_profile
          source $HOME/.bash_profile
      - name: Build APK
        script: |
          export PATH=$PATH:$HOME/Library/Python/3.*/bin
          buildozer android debug
    artifacts:
      - buildozer/bin/*.apk
