workflows:
  android-kivy-build:
    name: Build Kivy APK
    environment:
      vars:
        PYTHON_VERSION: 3.10.13
        JDK_VERSION: 17
        ANDROID_SDK_ROOT: /Users/builder/Library/Android/sdk
      python: 3.10.13
      java: 17
    scripts:
      - name: Setup Python and Buildozer
        script: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer
      - name: Initialize buildozer
        script: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
      - name: Install Android SDK Requirements
        script: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" || true
      - name: Build the APK
        script: |
          buildozer -v android debug
    artifacts:
      - build/*.apk
    publishing:
      email:
        recipients:
          - moclabel01@gmail.com
        notify:
          success: true
          failure: true
